-- Author      : cgiguy
-- Create Date : 7/19/2011
local L = LibStub("AceLocale-3.0"):NewLocale("SliceAdmiral", "enUS", true)
L["SALoaded"] = "SliceAdmiral %s loaded!! Options are under the SliceAdmiral tab in the Addons Interface menu"
L["ClickToMove"] = "Disable Click to Move"
L["PadLatency"] = "Pad Alerts with Latency"
L["ResetPossition"] = "Reset Position"
L["ResetPositionDecs"] = "Resets SliceAdmiral's position to upper left."
L["Main/info"] = "Click the + next to 'SliceAdmiral' in the list to the left for more options."
L["Main/Scale"] = "AddOn Scale"
L["Main/Width"] =  "Bar Width"
L["Main/oocFade"] = "Out of Combat Fade"
L["Main/Texture"] = "Bar Texture"
L["Main/Hide"] = "Hide outside combat"

L["TimerBars"] = "Timer Bars"
L["Combo"] = "Combo Points and Stats"
L["EnergyBar"] = "Energy Bar"
L["SoundEffects"] = "Sound Effects"
L["ResetDatabase"] = "Reset Database"
L["ResetDatabaseDesc"] = "Will Reset the Entire Database. This Should Fix most problems."

L["timer/dynamic"] = "Pandemic Timers"
L["timers/dynamic/desc"] = "Timers will start to decrease at 30% of their full duration. Does not work for certain abilities."
L["bar/prep"] = "Statusbar Countdown." --need new name
L["SoundSettings"] = "Sound Settings"
L["TickSound"] = "Tick Sound"
L["AlertSound"] = "Alert Sound"
L["alerts/enabled"] = "Enable Sounds"
L["SharedAbilites"] = "Shared Abilities"

L["ShowBar"] = "Show timer bar"

L["Bars/GrowUp"] = "Bars grow up"
L["Bars/SpellNames"] = "Show spellname"
L["Bars/Spellnames/Desc"] = "Enables spellname as text on the bars"
L["Bars/Sort"] = "Sort bars by duration"
L["Bars/ShowDoT"] = "Show DoT ticks"
L["Bars/DoTCrit"] = "Highlight DoT crits"
L["bars/color"] = "Bar Color"
L["bars/tickCd"] = "Tick Countdown"

L["Sound/MasterVolume"] = "Use Master Volume."
L["Sound/MasterDesc"] = "Play sound when sound effects are disabled."
L["Sound/OutOfCombat"] = "Play sound outside of combat."
L["Sound/Preview"] = "Pre-play Sound in options menu."

L["combo/Show"] = "Show Combo Points"
L["combo/texture"] = "Combo Point Texture"
L["tShow/anticipation"] = "Show Anticipation"
L["combo/statsheader"] = "Stats Bar Settings"
L["combo/showStats"] = "Show Stat Bar"
L["combo/megabuff"] = "Highlight when mega-buffed"
L["combo/armor"] = "Show Bandit's Guile Advancement"
L["combo/guile/desc"] = "Show counter on the statsbar for next advancement on Bandit's Guile"
L["ComboA/Color"] = "Anticipation Colour"
L["Combo/Color"] = "ComboPoints Colour"
L["combo/bf"] = "Blade Flurry target counter"
L["combo/bf/desc"] = "Replace Attack Speed with a Blade Flurry target counter. This only happens when you activate Blade Flurry."

L["energy/Show"] = "Show Energy Bar"
L["energy/ShowCombo"] = "Show Combopoint text"
L["energy/ShowAnti"] = "Show Anticipation text"
L["energy/mark1"] = "Energy Marker 1"
L["energy/mark2"] = "Energy Marker 2"
L["energy/transp"] = "Energy Transperancy"
L["energy/Color"] = "Energy Bar Colour"
L["energy/TextColor"] = "Energy Text Colour"
L["energy/CoTextColor"] = "Combo Point Text Color"
