-- Create Date : 3/11/2015
-- yuningning520
local L = LibStub("AceLocale-3.0"):NewLocale("SliceAdmiral", "zhCN")
if not L then return end

L["SALoaded"] = "SliceAdmiral %s 已载入!! 于 界面>插件>SliceAdmiral 设置。"
L["ClickToMove"] = "锁定点击移动"
L["PadLatency"] = "计算延迟"
L["ResetPossition"] = "重置位置"
L["ResetPositionDecs"] = "重置 SliceAdmiral 的位置到左上。"
L["Main/info"] = "点击 SliceAdmiral 左边的 + 进行更多设置。"
L["Main/Scale"] = "插件缩放"
L["Main/Width"] =  "整体宽度"
L["Main/oocFade"] = "脱离战斗渐隐"
L["Main/Texture"] = "材质"
L["Main/Hide"] = "脱战隐藏"

L["TimerBars"] = "计时条"
L["Combo"] = "连击点和统计栏"
L["EnergyBar"] = "能量条"
L["SoundEffects"] = "声音效果"
L["ResetDatabase"] = "重置数据"
L["ResetDatabaseDesc"] = "将重置所有数据。这应该可以解决大部分问题。"

L["timer/dynamic"] = "毒药计时器"
L["timers/dynamic/desc"] = "计时器将会在总持续时间的30%时下降。 有些技能不会生效。"
L["bar/prep"] = "状态条倒计时。"
L["SoundSettings"] = "音效设置"
L["TickSound"] = "跳伤音效"
L["AlertSound"] = "警报音效"
L["alerts/enabled"] = "启用音效"
L["SharedAbilites"] = "通用"
L["Assassination"] = "刺杀"
L["Combat"] = "战斗"
L["Subtlety"]= "敏锐"

L["ShowBar"] = "显示计时条"

L["Bars/GrowUp"] = "向上延伸计时条"
L["Bars/Sort"] = "按照持续时间排序"
L["Bars/ShowDoT"] = "显示跳伤"
L["Bars/DoTCrit"] = "高亮跳伤暴击"
L["bars/color"] = "颜色"
L["bars/tickCd"] = "跳伤倒计时"

L["Sound/MasterVolume"] = "使用主音量。"
L["Sound/MasterDesc"] = "当声音效果被禁用时播放声音。"
L["Sound/OutOfCombat"] = "非战斗时播放音效。"
L["Sound/Preview"] = "预先播放音效的选项菜单。"

L["combo/Show"] = "显示连击点"
L["tShow/anticipation"] = "显示预感点"
L["combo/statsheader"] = "统计栏设置"
L["combo/showStats"] = "显示统计栏"
L["combo/megabuff"] = "高亮大型增益"
L["combo/armor"] = "显示“刺客的狡诈”累积"
L["combo/guile/desc"] = "在状态条显示“刺客的狡诈”的累积计数。"
L["ComboA/Color"] = "预感点颜色"
L["Combo/Color"] = "连击点颜色"
L["combo/bf"] = "剑刃乱舞目标计数"
L["combo/bf/desc"] = "当您激活剑刃乱舞时，将攻击速度替换为剑刃乱舞目标计数器。"

L["energy/Show"] = "显示能量条"
L["energy/ShowCombo"] = "显示连击点数"
L["energy/ShowAnti"] = "显示预感点数"
L["energy/mark1"] = "能量标记1"
L["energy/mark2"] = "能量标记2"
L["energy/transp"] = "能量条透明度"
L["energy/Color"] = "能量条颜色"
L["energy/TextColor"] = "能量文字颜色"
L["energy/CoTextColor"] = "连击点文字颜色"
