local L = LibStub("AceLocale-3.0"):NewLocale("SliceAdmiral", "esES")
if not L then return end

L["alerts/enabled"] = "Habilitar Sonidos" -- Needs review
L["AlertSound"] = "Sonido de Alerta" -- Needs review
L["Assassination"] = "Asesinato" -- Needs review
L["bar/prep"] = "Cuenta atrás de Barra de Estado" -- Needs review
L["bars/color"] = "Color de Barra" -- Needs review
L["Bars/DoTCrit"] = "Resaltar DoT crits" -- Needs review
L["Bars/GrowUp"] = "Barras crecen hacia arriba" -- Needs review
L["Bars/ShowDoT"] = "Mostrar DoT ticks" -- Needs review
L["Bars/Sort"] = "Ordenar barras por duración" -- Needs review
L["bars/tickCd"] = "Cuenta atrás de Tick" -- Needs review
L["ClickToMove"] = "Deshabilitar Click para Mover" -- Needs review
L["Combat"] = "Combate" -- Needs review
L["Combo"] = "Puntos de Combo y Estadísticas" -- Needs review
L["ComboA/Color"] = "Color Anticipación" -- Needs review
L["combo/armor"] = "Mostar Avance de Astucia del Bandido" -- Needs review
L["combo/bf"] = "Aluvión de Acero contador de objetivos" -- Needs review
L["combo/bf/desc"] = "Reemplaza Velocidad de Ataque por un contador de objetivos para Aluvión de Acero. Esto solo pasa cuando activas Aluvión de Acero." -- Needs review
L["Combo/Color"] = "Color Puntos de Combo" -- Needs review
L["combo/guile/desc"] = "Mostrar contador en la barra de estado para el siguiente avance de Astucia del Bandido" -- Needs review
L["combo/megabuff"] = "Resaltar al estar mega-buffeado" -- Needs review
L["combo/Show"] = "Mostrar Puntos de Combo" -- Needs review
L["combo/showStats"] = "Mostar Barra de Estado" -- Needs review
L["combo/statsheader"] = "Configuración Barra de Estado" -- Needs review
L["EnergyBar"] = "Barra de Energía" -- Needs review
L["energy/Color"] = "Color de Barra de Energía" -- Needs review
L["energy/CoTextColor"] = "Color de Texto para Puntos de Combo" -- Needs review
L["energy/mark1"] = "Mardacor de Energía 1" -- Needs review
L["energy/mark2"] = "Marcador de Energía 2" -- Needs review
L["energy/Show"] = "Mostrar Barra de Energía" -- Needs review
L["energy/ShowAnti"] = "Mostrar texto para Anticipación" -- Needs review
L["energy/ShowCombo"] = "Mostrar texto para Puntos de Combo" -- Needs review
L["energy/TextColor"] = "Color de Texto para Energía" -- Needs review
L["energy/transp"] = "Transparencia de Energía" -- Needs review
L["Main/Hide"] = "Ocultar fuera de combate" -- Needs review
L["Main/info"] = "Click el + al lado de 'SliceAdmiral' en la lista de la izquierda para mas opciones." -- Needs review
L["Main/oocFade"] = "Desvanecer Fuera de Combate" -- Needs review
L["Main/Scale"] = "Escala AddOn" -- Needs review
L["Main/Texture"] = "Textura de Barra" -- Needs review
L["Main/Width"] = "Anchura de Barra" -- Needs review
L["PadLatency"] = "Coordinar Alertas con la Latencia" -- Needs review
L["ResetDatabase"] = "Reiniciar Base de datos" -- Needs review
L["ResetDatabaseDesc"] = "Reiniciará la Base de datos entera. Esto debería solucionar la mayoría de problemas." -- Needs review
L["ResetPositionDecs"] = "Reinicia la posición de SliceAdmiral." -- Needs review
L["ResetPossition"] = "Reiniciar Posición" -- Needs review
L["SALoaded"] = "SliceAdmiral %s cargado!! Opciones debajo de la sección SliceAdmiral en el menú de Interfaz de Addons" -- Needs review
L["SharedAbilites"] = "Habilidades Compartidas" -- Needs review
L["ShowBar"] = "Mostar barra temporizadora" -- Needs review
L["SoundEffects"] = "Efectos de Sonido" -- Needs review
L["Sound/MasterDesc"] = "Reproducir sonido cuando los efectos de sonido estén deshabilitados." -- Needs review
L["Sound/MasterVolume"] = "Usar Volumen Maestro" -- Needs review
L["Sound/OutOfCombat"] = "Reproducir sonido fuera de combate." -- Needs review
L["Sound/Preview"] = "Prueba el Sonido en el menú de opciones." -- Needs review
L["SoundSettings"] = "Configuración de Sonido" -- Needs review
L["Subtlety"] = "Sutileza" -- Needs review
L["TickSound"] = "Sonido de Tick" -- Needs review
L["TimerBars"] = "Barras Temporizadoras" -- Needs review
L["timer/dynamic"] = "Temporizador Pandemic" -- Needs review
L["timers/dynamic/desc"] = "Los temporizadores empezarán a disminuir al 30% de su duración total. No funciona con ciertas habilidades." -- Needs review
L["tShow/anticipation"] = "Mostrar Anticipación" -- Needs review
